package com.momo.memo;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.Setter;


@Setter
@Getter
@Entity
public class Memo {
	
	@Id	
	@GeneratedValue(strategy = GenerationType.IDENTITY) //1씩 증가하도록
	private Long id;   	    //메모일련번호(PK)
	
	@Column(columnDefinition = "VARCHAR2(1000)") 
	private String content;	//메모내용

}
/*
CREATE TABLE member (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    content VARCHAR2(1000)
);
*/